name: 'pnpm install'
description: 'Run pnpm install with cache enabled'
runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v2

    - name: Expose pnpm config as "$GITHUB_OUTPUT"
      id: pnpm-config
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Restore pnpm cache
      uses: actions/cache@v3
      id: cache-pnpm-store
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-
          pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install
